ENVIRONMENT:
  MAX_EPISODE_STEPS: 500
SIMULATOR:
  TURN_ANGLE: 30
  TILT_ANGLE: 30
  TURN_ANGLE_S: 10
  TILT_ANGLE_S: 10
  ACTION_SPACE_CONFIG: "v1"
  NUM_AGENTS: 2
  AGENT_0:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
    START_POSITION: [0, 0, 0]
    START_ROTATION: [0, 0, 0, 1]
  AGENT_1:
    SENSORS: ['RGB_SENSOR', 'DEPTH_SENSOR', 'SEMANTIC_SENSOR']
    HEIGHT: 0.88
    RADIUS: 0.18
    START_POSITION: [1, 1, 0]
    START_ROTATION: [0, 0, 0, 1]
  HABITAT_SIM_V0:
    GPU_DEVICE_ID: 0
    ALLOW_SLIDING: False 
  SEMANTIC_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  RGB_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    POSITION: [0, 0.88, 0]
  DEPTH_SENSOR:
    WIDTH: 640
    HEIGHT: 480
    HFOV: 79
    MIN_DEPTH: 0.5
    MAX_DEPTH: 5.0
    POSITION: [0, 0.88, 0]
TASK:
  TYPE: ObjectNav-v1
  POSSIBLE_ACTIONS: ["STOP", "MOVE_FORWARD", "TURN_LEFT", "TURN_RIGHT", "LOOK_UP", "LOOK_DOWN"]
  SENSORS: ['OBJECTGOAL_SENSOR', 'GPS_SENSOR', 'COMPASS_SENSOR']
  GOAL_SENSOR_UUID: objectgoal
  MEASUREMENTS: ['Multi_Agent_Multi_Goals']
  DISTANCE_TO_GOAL:
    DISTANCE_TO: VIEW_POINTS
  SUCCESS:
    SUCCESS_DISTANCE: 0.2

DATASET:
  TYPE: ObjectNav-v1
  SPLIT: val
  DATA_PATH: /Data/hm3d/datasets/objectnav/objectnav_hm3d_v2/{split}/{split}.json.gz
  SCENES_DIR: /Data/hm3d/scene_datasets_v0.2/

